# PakWheels Car Listings Data Cleaning & Validation

This notebook will guide you through loading, inspecting, cleaning, and flattening your PakWheels car listings data for analysis.

## 1. Import Required Libraries

We'll use pandas for data manipulation and numpy for numerical operations.

In [29]:
import pandas as pd
import numpy as np
import json

## 2. Load the Data

Read the car listings CSV file into a pandas DataFrame.

In [30]:
csv_path = 'data/pakwheels_listings.csv'
df = pd.read_csv(csv_path)
print("Shape:", df.shape)
df.head()

Shape: (47157, 7)

,id,car_url,data,status,first_seen,last_seen,updated_at
0,1,https://www.pakwheels.com/used-cars/honda-br-v...,"{""url"": ""https://www.pakwheels.com/used-cars/h...",active,2025-07-03,2025-07-03,2025-07-03 17:36:28.817102
1,2,https://www.pakwheels.com/used-cars/mg-hs-2025...,"{""url"": ""https://www.pakwheels.com/used-cars/m...",active,2025-07-03,2025-07-03,2025-07-03 17:36:31.58861
2,3,https://www.pakwheels.com/used-cars/mg-4-2025-...,"{""url"": ""https://www.pakwheels.com/used-cars/m...",active,2025-07-03,2025-07-03,2025-07-03 17:36:33.155228
3,4,https://www.pakwheels.com/used-cars/daihatsu-h...,"{""url"": ""https://www.pakwheels.com/used-cars/d...",active,2025-07-03,2025-07-03,2025-07-03 17:36:36.554833
4,5,https://www.pakwheels.com/used-cars/honda-civi...,"{""url"": ""https://www.pakwheels.com/used-cars/h...",active,2025-07-03,2025-07-03,2025-07-03 17:36:39.320452

## 3. Inspect DataFrame Structure

Check the columns, data types, and a preview of the data.

In [31]:
print("Columns:", df.columns.tolist())
df.info()
df.head()

Columns: ['id', 'car_url', 'data', 'status', 'first_seen', 'last_seen', 'updated_at']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47157 entries, 0 to 47156
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          47157 non-null  int64
 1   car_url     47157 non-null  object
 2   data        47157 non-null  object
 3   status      47157 non-null  object
 4   first_seen  47157 non-null  object
 5   last_seen   47157 non-null  object
 6   updated_at  47157 non-null  object
dtypes: int64(1), object(6)
memory usage: 2.5+ MB

,id,car_url,data,status,first_seen,last_seen,updated_at
0,1,https://www.pakwheels.com/used-cars/honda-br-v...,"{""url"": ""https://www.pakwheels.com/used-cars/h...",active,2025-07-03,2025-07-03,2025-07-03 17:36:28.817102
1,2,https://www.pakwheels.com/used-cars/mg-hs-2025...,"{""url"": ""https://www.pakwheels.com/used-cars/m...",active,2025-07-03,2025-07-03,2025-07-03 17:36:31.58861
2,3,https://www.pakwheels.com/used-cars/mg-4-2025-...,"{""url"": ""https://www.pakwheels.com/used-cars/m...",active,2025-07-03,2025-07-03,2025-07-03 17:36:33.155228
3,4,https://www.pakwheels.com/used-cars/daihatsu-h...,"{""url"": ""https://www.pakwheels.com/used-cars/d...",active,2025-07-03,2025-07-03,2025-07-03 17:36:36.554833
4,5,https://www.pakwheels.com/used-cars/honda-civi...,"{""url"": ""https://www.pakwheels.com/used-cars/h...",active,2025-07-03,2025-07-03,2025-07-03 17:36:39.320452

## 4. Check for Missing Values

See how many missing values are present in each column.

In [32]:
df.isnull().sum()

id            0
car_url       0
data          0
status        0
first_seen    0
last_seen     0
updated_at    0
dtype: int64

## 5. Handle Missing Data

Fill missing numeric values with the median and string/object columns with empty strings.

In [33]:
df_filled = df.copy()
for col in df_filled.select_dtypes(include=[np.number]).columns:
    df_filled[col] = df_filled[col].fillna(df_filled[col].median())
for col in df_filled.select_dtypes(include='object').columns:
    df_filled[col] = df_filled[col].fillna('')
df_filled.isnull().sum()

id            0
car_url       0
data          0
status        0
first_seen    0
last_seen     0
updated_at    0
dtype: int64

## 6. Remove Duplicates

Drop duplicate rows to ensure data quality.

In [34]:
df_cleaned = df_filled.drop_duplicates()
print("Rows after cleaning:", df_cleaned.shape[0])

Rows after cleaning: 47157

## 7. Validate and Convert Data Types

Convert columns like 'price' to numeric if needed.

In [35]:
if 'price' in df_cleaned.columns:
    df_cleaned['price'] = pd.to_numeric(df_cleaned['price'], errors='coerce')
df_cleaned.dtypes

id             int64
car_url       object
data          object
status        object
first_seen    object
last_seen     object
updated_at    object
dtype: object

## 8. Clean and Standardize Column Names

Make column names lowercase, strip whitespace, and replace spaces with underscores.

In [36]:
df_cleaned.columns = df_cleaned.columns.str.strip().str.lower().str.replace(' ', '_')
for col in df_cleaned.select_dtypes(include='object').columns:
    df_cleaned[col] = df_cleaned[col].str.strip()
df_cleaned.head()

,id,car_url,data,status,first_seen,last_seen,updated_at
0,1,https://www.pakwheels.com/used-cars/honda-br-v...,"{""url"": ""https://www.pakwheels.com/used-cars/h...",active,2025-07-03,2025-07-03,2025-07-03 17:36:28.817102
1,2,https://www.pakwheels.com/used-cars/mg-hs-2025...,"{""url"": ""https://www.pakwheels.com/used-cars/m...",active,2025-07-03,2025-07-03,2025-07-03 17:36:31.58861
2,3,https://www.pakwheels.com/used-cars/mg-4-2025-...,"{""url"": ""https://www.pakwheels.com/used-cars/m...",active,2025-07-03,2025-07-03,2025-07-03 17:36:33.155228
3,4,https://www.pakwheels.com/used-cars/daihatsu-h...,"{""url"": ""https://www.pakwheels.com/used-cars/d...",active,2025-07-03,2025-07-03,2025-07-03 17:36:36.554833
4,5,https://www.pakwheels.com/used-cars/honda-civi...,"{""url"": ""https://www.pakwheels.com/used-cars/h...",active,2025-07-03,2025-07-03,2025-07-03 17:36:39.320452

## 9. Save Cleaned Data

Export the cleaned DataFrame to a new CSV file.

In [37]:
df_cleaned.to_csv('data/pakwheels_listings_cleaned.csv', index=False)

## 10. Extract and Flatten Car Details from the `data` Column

If your car details are stored as JSON or dict in the `data` column, flatten them for analysis.

In [38]:
def ensure_dict(val):
    if isinstance(val, str):
        try:
            return json.loads(val)
        except Exception:
            return {}
    elif isinstance(val, dict):
        return val
    else:
        return {}

if 'data' in df_cleaned.columns:
    df_cleaned['data'] = df_cleaned['data'].apply(ensure_dict)
    details_df = pd.DataFrame(df_cleaned['data'].tolist())
    # Optionally, join with other columns (like id, car_url)
    if 'id' in df_cleaned.columns:
        details_df['id'] = df_cleaned['id']
    if 'car_url' in df_cleaned.columns:
        details_df['car_url'] = df_cleaned['car_url']
    details_df.head()
else:
    print("No 'data' column found in the DataFrame.")

## 11. Preview Flattened Car Details

Display the first few rows and columns of the normalized car details DataFrame.

In [39]:
print('Columns:', details_df.columns.tolist())
details_df.head(10)

Columns: ['url', 'name', 'color', 'price', 'engine', 'mileage', 'assembly', 'location', 'body_type', 'fuel_type', 'seller_info', 'transmission', 'registration_city', 'id', 'car_url']

,url,name,color,price,engine,mileage,assembly,location,body_type,fuel_type,seller_info,transmission,registration_city,id,car_url
0,https://www.pakwheels.com/used-cars/honda-br-v...,,,,,,,,,,,,,1,https://www.pakwheels.com/used-cars/honda-br-v...
1,https://www.pakwheels.com/used-cars/mg-hs-2025...,,,,,,,,,,,,,2,https://www.pakwheels.com/used-cars/mg-hs-2025...
2,https://www.pakwheels.com/used-cars/mg-4-2025-...,,,,,,,,,,,,,3,https://www.pakwheels.com/used-cars/mg-4-2025-...
3,https://www.pakwheels.com/used-cars/daihatsu-h...,,,,,,,,,,,,,4,https://www.pakwheels.com/used-cars/daihatsu-h...
4,https://www.pakwheels.com/used-cars/honda-civi...,,,,,,,,,,,,,5,https://www.pakwheels.com/used-cars/honda-civi...
5,https://www.pakwheels.com/used-cars/suzuki-meh...,,,,,,,,,,,,,6,https://www.pakwheels.com/used-cars/suzuki-meh...
6,https://www.pakwheels.com/used-cars/toyota-cor...,,,,,,,,,,,,,7,https://www.pakwheels.com/used-cars/toyota-cor...
7,https://www.pakwheels.com/used-cars/honda-civi...,,,,,,,,,,,,,8,https://www.pakwheels.com/used-cars/honda-civi...
8,https://www.pakwheels.com/used-cars/suzuki-meh...,,,,,,,,,,,,,9,https://www.pakwheels.com/used-cars/suzuki-meh...
9,https://www.pakwheels.com/used-cars/toyota-cor...,,,,,,,,,,,,,10,https://www.pakwheels.com/used-cars/toyota-cor...

In [41]:
# Show a single sample record to verify all fields are present
if not details_df.empty:
    print('Sample record:')
    print(details_df.iloc[0])
    # Print all keys and their values for full inspection
    for k, v in details_df.iloc[0].items():
        print(f"{k}: {v}")
else:
    print('No data found in details_df.')

Sample record:
url                  https://www.pakwheels.com/used-cars/honda-br-v...
name
color
price
engine
mileage
assembly
location
body_type
fuel_type
seller_info
transmission
registration_city
id                                                                   1
car_url              https://www.pakwheels.com/used-cars/honda-br-v...
Name: 0, dtype: object
url: https://www.pakwheels.com/used-cars/honda-br-v-2017-for-sale-in-gujrat-10275738
name:
color:
price:
engine:
mileage:
assembly:
location:
body_type:
fuel_type:
seller_info:
transmission:
registration_city:
id: 1
car_url: https://www.pakwheels.com/used-cars/honda-br-v-2017-for-sale-in-gujrat-10275738

In [ ]:
# Show a single sample record to verify all fields are present
if not details_df.empty:
    print('Sample record:')
    print(details_df.iloc[0])
    # Print all keys and their values for full inspection
    for k, v in details_df.iloc[0].items():
        print(f"{k}: {v}")
else:
    print('No data found in details_df.')

Sample record:
url                  https://www.pakwheels.com/used-cars/honda-br-v...
name
color
price
engine
mileage
assembly
location
body_type
fuel_type
seller_info
transmission
registration_city
id                                                                   1
car_url              https://www.pakwheels.com/used-cars/honda-br-v...
Name: 0, dtype: object
url: https://www.pakwheels.com/used-cars/honda-br-v-2017-for-sale-in-gujrat-10275738
name:
color:
price:
engine:
mileage:
assembly:
location:
body_type:
fuel_type:
seller_info:
transmission:
registration_city:
id: 1
car_url: https://www.pakwheels.com/used-cars/honda-br-v-2017-for-sale-in-gujrat-10275738